version: '2'
services:
  database:
    image: postgres:9.6.0
    volumes:
      - pgauth:/var/lib/postgresql/data
      - ./init/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  auth:
    image: jboss/keycloak-postgres:3.0.0.Final
    ports:
      - "30303:8080"
    volumes:
      - ./init/keycloak:/tmp/keycloak-export
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=database
    links:
      - database
volumes:
  pgauth:
    external: true