version: '2.1'
services:
  database:
    image: postgres:9.6.0
    volumes:
      - pgauth:/var/lib/postgresql/data
      - ./init/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  auth:
    image: jboss/keycloak-postgres:3.0.0.Final
    ports:
      - "30303:8080"
    volumes:
      - "${PWD-.}/init/keycloak:/tmp/keycloak-export"
      - "${PWD-.}/themes/address:/opt/jboss/keycloak/themes/address"
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=database
    links:
      - database
volumes:
  pgauth:
